In [3]:
# The vector pioneers has already been created for you
pioneers <- c("GAUSS:1777", "BAYES:1702", "PASCAL:1623", "PEARSON:1857")

# Split names from birth year
split_math <- strsplit(pioneers, split = ":")

In [4]:
split_math

[[1]]
[1] "GAUSS" "1777" 

[[2]]
[1] "BAYES" "1702" 

[[3]]
[1] "PASCAL" "1623"  

[[4]]
[1] "PEARSON" "1857"

In [5]:
unlist(split_math)

[1] "GAUSS"   "1777"    "BAYES"   "1702"    "PASCAL"  "1623"    "PEARSON"
[8] "1857"

In [8]:
# The vector pioneers has already been created for you
pioneers <- c("GAUSS:1777", "BAYES:1702", "PASCAL:1623", "PEARSON:1857")

# Split names from birth year
split_math <- strsplit(pioneers, split = ":")

# Convert to lowercase strings: split_low
# lapply(X, FUN, …)

split_low <- lapply(split_math,tolower)
split_low

[[1]]
[1] "gauss" "1777" 

[[2]]
[1] "bayes" "1702" 

[[3]]
[1] "pascal" "1623"  

[[4]]
[1] "pearson" "1857"

In [9]:
# Take a look at the structure of split_low
str(split_low)

List of 4
 $ : chr [1:2] "gauss" "1777"
 $ : chr [1:2] "bayes" "1702"
 $ : chr [1:2] "pascal" "1623"
 $ : chr [1:2] "pearson" "1857"


In [12]:
# Code from previous exercise:
pioneers <- c("GAUSS:1777", "BAYES:1702", "PASCAL:1623", "PEARSON:1857")
split <- strsplit(pioneers, split = ":")
split_low <- lapply(split, tolower)

# Write function select_first()
select_first <- function(x) {
  x[1]
}

# Apply select_first() over split_low: names

names <- lapply(split_low, select_first)


# Write function select_second()

select_second <- function(x) {
  x[2]
}


# Apply select_second() over split_low: years

years <- lapply(split_low, select_second)


# print
names
years

[[1]]
[1] "gauss"

[[2]]
[1] "bayes"

[[3]]
[1] "pascal"

[[4]]
[1] "pearson"

[[1]]
[1] "1777"

[[2]]
[1] "1702"

[[3]]
[1] "1623"

[[4]]
[1] "1857"

In [13]:
# When you create a function, you can use the assignment operator to give the function a name. It's perfectly possible, however, to not give the function a name. This is called an anonymous function:

# Named function
triple <- function(x) { 3 * x }

# Anonymous function with same implementation
function(x) { 3 * x }

# Use anonymous function inside lapply()
lapply(list(1,2,3), function(x) { 3 * x })

function(x) { 3 * x }

[[1]]
[1] 3

[[2]]
[1] 6

[[3]]
[1] 9

In [20]:
# Transform the calls of lapply() such that they use an anonymous function that does the same thing.

# split_low has been created for you

# Transform: use anonymous function inside lapply
select_first <- function(x) {
  x[1]
}
names <- lapply(split_low, select_first)
#is the same as
names <- lapply(split_low, function(x) {x[1]})

# Transform: use anonymous function inside lapply
select_second <- function(x) {
  x[2]
}
years <- lapply(split_low, select_second)
#is the same as
names <- lapply(split_low, function(x) {x[1]})

#print 
split_low
names
years

[[1]]
[1] "gauss" "1777" 

[[2]]
[1] "bayes" "1702" 

[[3]]
[1] "pascal" "1623"  

[[4]]
[1] "pearson" "1857"

[[1]]
[1] "gauss"

[[2]]
[1] "bayes"

[[3]]
[1] "pascal"

[[4]]
[1] "pearson"

[[1]]
[1] "1777"

[[2]]
[1] "1702"

[[3]]
[1] "1623"

[[4]]
[1] "1857"

In [23]:
# lapply() provides a way to handle functions that require more than one argument, such as the multiply() function:
multiply <- function(x, factor) {
  x * factor
}

In [24]:
lapply(list(1,2,3), multiply, factor = 3)

[[1]]
[1] 3

[[2]]
[1] 6

[[3]]
[1] 9

In [25]:
lapply(list(1,2,3), multiply, factor = 4)

[[1]]
[1] 4

[[2]]
[1] 8

[[3]]
[1] 12

In [27]:
# Definition of split_low
pioneers <- c("GAUSS:1777", "BAYES:1702", "PASCAL:1623", "PEARSON:1857")
split <- strsplit(pioneers, split = ":")
split_low <- lapply(split, tolower)

# Generic select function
select_el <- function(x, index) {
  x[index]
}

# Use lapply() twice on split_low: names and years

names <- lapply(split_low, select_el, index = 1)
years <- lapply(split_low, select_el, index = 2)

#prints
names
years

[[1]]
[1] "gauss"

[[2]]
[1] "bayes"

[[3]]
[1] "pascal"

[[4]]
[1] "pearson"

[[1]]
[1] "1777"

[[2]]
[1] "1702"

[[3]]
[1] "1623"

[[4]]
[1] "1857"

In [28]:
# returns NULL here
lapply(list(1, "a", TRUE), str)

 num 1
 chr "a"
 logi TRUE


[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

In [29]:
# but returns structure here
str(TRUE)

 logi TRUE


In [30]:
# lapply() always returns a list, no matter the input

lapply(split_low, function(x) {
  if (nchar(x[1]) > 5) {
    return(NULL)
  } else {
    return(x[2])
  }
})

[[1]]
[1] "1777"

[[2]]
[1] "1702"

[[3]]
NULL

[[4]]
NULL

In [33]:
#cities: sapply()
cities <- c("New York", "Paris", "London", "Tokyo", "Rio de Janeiro", "Cape Town")
lapply(cities,nchar)

[[1]]
[1] 8

[[2]]
[1] 5

[[3]]
[1] 6

[[4]]
[1] 5

[[5]]
[1] 14

[[6]]
[1] 9

In [34]:
unlist(lapply(cities,nchar))

[1]  8  5  6  5 14  9

In [35]:
sapply(cities,nchar)

New York          Paris         London          Tokyo Rio de Janeiro 
             8              5              6              5             14 
     Cape Town 
             9

In [36]:
sapply(cities, nchar, USE.NAMES = FALSE)

[1]  8  5  6  5 14  9

In [40]:
first_and_last <- function(name) {
    name <- gsub(" ", "", name) #"" makes first = ''; have to use " "
    letters <- strsplit(name, split = "")[[1]]
    c(first = min(letters), last = max(letters))
}
first_and_last('New York')

#first and last letter in the alphabet of name

first  last 
  "e"   "Y"

In [41]:
sapply(cities, first_and_last)

New York Paris London Tokyo Rio de Janeiro Cape Town
first e        a     d      k     a              a        
last  Y        s     o      y     R              w

In [55]:
temp <- list(c(3,7,9,6, -1), c(6,9,12,13,5), c(4,8,3,-1,-3), c(1,4,7,2,-2), c(5,7,9,4,2), c(-3,5,8,9,4), c(3,6,9,4,1))

In [69]:
temp

[[1]]
[1]  3  7  9  6 -1

[[2]]
[1]  6  9 12 13  5

[[3]]
[1]  4  8  3 -1 -3

[[4]]
[1]  1  4  7  2 -2

[[5]]
[1] 5 7 9 4 2

[[6]]
[1] -3  5  8  9  4

[[7]]
[1] 3 6 9 4 1

In [57]:
# sapply(X, FUN, ...)

# temp has already been defined in the workspace
str(temp)
# Use lapply() to find each day's minimum temperature
lapply(temp, min)

# Use sapply() to find each day's minimum temperature
sapply(temp,min)

# Use lapply() to find each day's maximum temperature
lapply(temp,max)

# Use sapply() to find each day's maximum temperature
sapply(temp,max)

# https://campus.datacamp.com/courses/intermediate-r/chapter-4-the-apply-family?ex=8 

List of 7
 $ : num [1:5] 3 7 9 6 -1
 $ : num [1:5] 6 9 12 13 5
 $ : num [1:5] 4 8 3 -1 -3
 $ : num [1:5] 1 4 7 2 -2
 $ : num [1:5] 5 7 9 4 2
 $ : num [1:5] -3 5 8 9 4
 $ : num [1:5] 3 6 9 4 1


[[1]]
[1] -1

[[2]]
[1] 5

[[3]]
[1] -3

[[4]]
[1] -2

[[5]]
[1] 2

[[6]]
[1] -3

[[7]]
[1] 1

[1] -1  5 -3 -2  2 -3  1

[[1]]
[1] 9

[[2]]
[1] 13

[[3]]
[1] 8

[[4]]
[1] 7

[[5]]
[1] 9

[[6]]
[1] 9

[[7]]
[1] 9

[1]  9 13  8  7  9  9  9

In [58]:
# temp is already defined in the workspace

# Finish function definition of extremes_avg
extremes_avg <- function(x) {
  (min(x) + max(x)) / 2
}

# Apply extremes_avg() over temp using sapply()
sapply(temp, extremes_avg)

# Apply extremes_avg() over temp using lapply()
lapply(temp, extremes_avg)

[1] 4.0 9.0 2.5 2.5 5.5 3.0 5.0

[[1]]
[1] 4

[[2]]
[1] 9

[[3]]
[1] 2.5

[[4]]
[1] 2.5

[[5]]
[1] 5.5

[[6]]
[1] 3

[[7]]
[1] 5

In [60]:
# Create a function that returns min and max of a vector: extremes
extremes <- function(x) {
    c(min = min(x), max = max(x))
  }
 
# Apply extremes() over temp with sapply()

sapply(temp, extremes)

# Apply extremes() over temp with lapply()

lapply(temp, extremes)

# temp is already available in the workspace
 
# Create a function that returns min and max of a vector: extremes
extremes <- function(x) {
    c(min = min(x), max = max(x))
  }

# Apply extremes() over temp with sapply()

sapply(temp, extremes)

# Apply extremes() over temp with lapply()

lapply(temp, extremes)


##sapply() did a great job at simplifying the rather uninformative 'list of vectors' that lapply() returns. It actually returned a nicely formatted matrix!

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
min -1    5   -3   -2   2    -3   1   
max  9   13    8    7   9     9   9

[[1]]
min max 
 -1   9 

[[2]]
min max 
  5  13 

[[3]]
min max 
 -3   8 

[[4]]
min max 
 -2   7 

[[5]]
min max 
  2   9 

[[6]]
min max 
 -3   9 

[[7]]
min max 
  1   9

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
min -1    5   -3   -2   2    -3   1   
max  9   13    8    7   9     9   9

[[1]]
min max 
 -1   9 

[[2]]
min max 
  5  13 

[[3]]
min max 
 -3   8 

[[4]]
min max 
 -2   7 

[[5]]
min max 
  2   9 

[[6]]
min max 
 -3   9 

[[7]]
min max 
  1   9

In [64]:
# temp is already prepared for you in the workspace

# Definition of below_zero()
below_zero <- function(x) {
    return(x[x < 0])
  }

# Apply below_zero over temp using sapply(): freezing_s
freezing_s <- sapply(temp, below_zero)

# Apply below_zero over temp using lapply(): freezing_l
freezing_l <- lapply(temp, below_zero)

In [65]:
#print

freezing_l

freezing_s

# Are freezing_s and freezing_l identical?

identical(freezing_l, freezing_s)

## Given that the length of the output of below_zero() changes for different input vectors, sapply() is not able to nicely convert the output of lapply() to a nicely formatted matrix. Instead, the output values of sapply() and lapply() are exactly the same, as shown by the TRUE output of identical()

[[1]]
[1] -1

[[2]]
numeric(0)

[[3]]
[1] -1 -3

[[4]]
[1] -2

[[5]]
numeric(0)

[[6]]
[1] -3

[[7]]
numeric(0)

[[1]]
[1] -1

[[2]]
numeric(0)

[[3]]
[1] -1 -3

[[4]]
[1] -2

[[5]]
numeric(0)

[[6]]
[1] -3

[[7]]
numeric(0)

[1] TRUE

In [67]:

# In this exercise, you'll see how sapply() reacts when it is used to apply a function that returns NULL over a vector or a list.

# Definition of print_info()
print_info <- function(x) {
    cat("The average temperature is", mean(x), "\n")
  }

# Apply print_info() over temp using sapply()
 
sapply(temp, print_info)

# Apply print_info() over temp using lapply()

lapply(temp, print_info)

# Notice here that, quite surprisingly, sapply() does not simplify the list of NULL's. That's because the 'vector-version' of a list of NULL's would simply be a NULL, which is no longer a vector with the same length as the input.

The average temperature is 4.8 
The average temperature is 9 
The average temperature is 2.2 
The average temperature is 2.4 
The average temperature is 5.4 
The average temperature is 4.6 
The average temperature is 4.6 


[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

[[4]]
NULL

[[5]]
NULL

[[6]]
NULL

[[7]]
NULL

The average temperature is 4.8 
The average temperature is 9 
The average temperature is 2.2 
The average temperature is 2.4 
The average temperature is 5.4 
The average temperature is 4.6 
The average temperature is 4.6 


[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

[[4]]
NULL

[[5]]
NULL

[[6]]
NULL

[[7]]
NULL

In [68]:
# temp is already available in the workspace
temp

# Definition of basics()
basics <- function(x) {
    c(min = min(x), mean = mean(x), max = max(x))
  }
 
# Apply basics() over temp using vapply()

vapply(temp, basics, numeric(3))

[[1]]
[1]  3  7  9  6 -1

[[2]]
[1]  6  9 12 13  5

[[3]]
[1]  4  8  3 -1 -3

[[4]]
[1]  1  4  7  2 -2

[[5]]
[1] 5 7 9 4 2

[[6]]
[1] -3  5  8  9  4

[[7]]
[1] 3 6 9 4 1

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
min  -1.0  5   -3.0 -2.0 2.0  -3.0 1.0 
mean  4.8  9    2.2  2.4 5.4   4.6 4.6 
max   9.0 13    8.0  7.0 9.0   9.0 9.0

In [71]:
# temp is already available in the workspace

# Definition of basics()
basics <- function(x) {
  c(min = min(x), mean = mean(x), max = max(x))
}

# Apply basics() over temp using vapply()
# vapply(X, FUN, FUN.VALUE, ..., USE.NAMES = TRUE)
vapply(temp, basics, numeric(3))

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
min  -1.0  5   -3.0 -2.0 2.0  -3.0 1.0 
mean  4.8  9    2.2  2.4 5.4   4.6 4.6 
max   9.0 13    8.0  7.0 9.0   9.0 9.0

In [75]:
#Inspect code with str() 

# Definition of the basics() function
basics <- function(x) {
  c(min = min(x), mean = mean(x), median = median(x), max = max(x))
}


# Fix the error:

# str(vapply(temp, basics, numeric(3)))

# Error: values must be length 3, but FUN(X[[1]]) result is length 4


str(vapply(temp, basics, numeric(4)))

#

 num [1:4, 1:7] -1 4.8 6 9 5 9 9 13 -3 2.2 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:4] "min" "mean" "median" "max"
  ..$ : NULL


In [ ]:
# vapply() can be considered a more robust version of sapply(), because you explicitly restrict the output of the function you want to apply. Converting your sapply() expressions in your own R scripts to vapply() expressions is therefore a good practice

In [77]:
#Convert all the sapply() expressions to their vapply() counterparts. Their results should be exactly the same; you're only adding robustness. You'll need the templates numeric(1) and logical(1).

# Convert to vapply() expression
sapply(temp, max)
vapply(temp, max, numeric(1))

# Convert to vapply() expression
sapply(temp, function(x, y) { mean(x) > y }, y = 5)
vapply(temp, function(x, y) { mean(x) > y }, y = 5, logical(1))

[1]  9 13  8  7  9  9  9

[1]  9 13  8  7  9  9  9

[1] FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE

[1] FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE